# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-01 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=64, verbose_name='\u6218\u961f'),
        ),
    ]
