# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-29 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(default=None, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='nikename',
            field=models.CharField(default=None, max_length=64, null=True),
        ),
    ]
