# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-31 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_auth', '0002_auto_20180329_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='introduction',
            field=models.TextField(null=True, verbose_name='\u7b80\u4ecb'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(default=None, max_length=16, null=True, verbose_name='\u624b\u673a\u53f7'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nikename',
            field=models.CharField(default=None, max_length=64, null=True, verbose_name='\u6635\u79f0'),
        ),
    ]
