# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-09 14:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_auth', '0003_auto_20180331_1140'),
        ('common_auth', '0002_auto_20180401_1936'),
    ]

    operations = [
    ]
