# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-26 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_acc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': '\u6e38\u620f\u8d26\u53f7', 'verbose_name_plural': '\u6e38\u620f\u8d26\u53f7'},
        ),
        migrations.AlterModelOptions(
            name='server',
            options={'verbose_name': '\u670d\u52a1\u5668', 'verbose_name_plural': '\u670d\u52a1\u5668'},
        ),
        migrations.AlterField(
            model_name='account',
            name='acc_number',
            field=models.CharField(max_length=32, verbose_name=b'\xe8\xb4\xa6\xe5\x8f\xb7'),
        ),
        migrations.AlterField(
            model_name='account',
            name='acc_password',
            field=models.CharField(max_length=64, verbose_name=b'\xe8\xb4\xa6\xe5\x8f\xb7\xe5\xaf\x86\xe7\xa0\x81'),
        ),
        migrations.AlterField(
            model_name='account',
            name='nikename',
            field=models.CharField(max_length=64, verbose_name=b'\xe6\x98\xb5\xe7\xa7\xb0'),
        ),
        migrations.AlterField(
            model_name='account',
            name='owner',
            field=models.CharField(max_length=64, verbose_name=b'\xe6\x8b\xa5\xe6\x9c\x89\xe8\x80\x85'),
        ),
        migrations.AlterField(
            model_name='server',
            name='name',
            field=models.CharField(max_length=64, verbose_name=b'\xe5\xa4\xa7\xe5\x8c\xba'),
        ),
    ]
